apiVersion: v1
kind: Namespace
metadata:
  name: python-api-1
  labels:
    # Standard Kubernetes labels
    kubernetes.io/metadata.name: python-api-1
    
    # Environment labels
    environment: development
    
    # Application labels
    app.kubernetes.io/name: python-api-1
    app.kubernetes.io/part-of: k8s-enterprise-lab
    app.kubernetes.io/managed-by: gitops
    
    # Team and ownership
    team: platform-engineering
    owner: gitops-team
    
    # Cost tracking
    cost-center: engineering
    
    # Monitoring and observability
    logging: enabled
    
    # Security
    security-level: standard
    
    # Compliance
    compliance-tier: medium
  annotations:
    # Description
    description: "Namespace for Python API 1 application"
    
    # Contact information
    contact: "platform-engineering@example.com"
    
    # Change management
    change-management: "gitops"
    
    # Cost tracking
    cost-center-code: "ENG-001"
    

    
    # Security
    security-contact: "security@example.com"
    
    # Compliance
    compliance-owner: "compliance@example.com"
    
    # GitOps
    gitops.repo: "https://github.com/medaqueno/k8s-lab-gitops.git"
    gitops.path: "namespaces/overlays/<environment>"