apiVersion: v1
kind: ResourceQuota
metadata:
  name: standard-quota
spec:
  hard:
    # Compute resources
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    
    # Storage resources
    requests.storage: 50Gi
    
    # Object counts
    pods: "20"
    services: "10"
    configmaps: "20"
    secrets: "20"
    persistentvolumeclaims: "10"
    
    # Service resources
    services.loadbalancers: "2"
    services.nodeports: "0"