apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: python-api-1-hpa
  labels:
    # Application labels
    app.kubernetes.io/name: python-api-1
    app.kubernetes.io/instance: python-api-1-deployment
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: k8s-enterprise-lab
    app.kubernetes.io/managed-by: gitops
    
    # Environment labels
    environment: development
    tier: development
    
    # HPA-specific labels
    autoscaling-type: horizontal
    
    # Team and ownership
    team: platform-engineering
    owner: gitops-team
    
    # Monitoring labels
    monitoring: enabled
    logging: enabled
  annotations:
    # Description
    description: "Horizontal Pod Autoscaler for Python API 1 development environment"
    
    # GitOps metadata
    gitops.repo: "https://github.com/medaqueno/k8s-lab-gitops.git"
    gitops.path: "apps/python-api-1/overlays/dev"
    
    # Contact information
    contact: "platform-engineering@example.com"
    
    # Change management
    change-management: "gitops"
    
    # Security
    security-level: standard
    compliance-tier: medium
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-api-1-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Percent
          value: 20
          periodSeconds: 60
        - type: Pods
          value: 2
          periodSeconds: 60
      selectPolicy: Max