apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: dev-demo-app

commonLabels:
  environment: dev
  tier: application

images:
  - name: ghcr.io/medaqueno/k8s-lab-apps-demo-app
    newTag: dev-latest

patches:
  - target:
      kind: HTTPRoute
      name: demo-app-route
    patch: |-
      - op: replace
        path: /spec/rules/0/matches/0/path/value
        value: /dev/demo-app
