name: Reusable CI/CD Engine
on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
    secrets:
      GIT_OPS_SSH_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.vars.outputs.sha_short }}
    steps:
      - uses: actions/checkout@v4
      - id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.sha_short }}

  update-gitops:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: medaqueno/k8s-lab-gitops
          ssh-key: ${{ secrets.GIT_OPS_SSH_KEY }}
      - name: Update Kustomize Image
        run: |
          cd apps/${{ inputs.app_name }}/base
          kustomize edit set image app-image=ghcr.io/${{ github.repository }}:${{ needs.build.outputs.sha }}
      - name: Commit & Push
        run: |
          git config user.name "GitOps Bot"
          git config user.email "bot@gitops.com"
          git add .
          git commit -m "deploy: update ${{ inputs.app_name }} to ${{ needs.build.outputs.sha }}"
          git push
