on:
  workflow_call:
    secrets:
      GIT_OPS_SSH_KEY:
        required: true
        description: "Clave SSH privada con permisos de escritura en el repositorio GitOps."
    inputs:
      app_name:
        required: true
        type: string
        description: "Nombre de la aplicación para etiquetado."

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.vars.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag variables
        id: vars
        run: |
          SHA_SHORT=$(git rev-parse --short HEAD)
          echo "image_tag=$SHA_SHORT" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.image_tag }}
            ghcr.io/${{ github.repository }}:latest

  update-gitops:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: medaqueno/k8s-lab-gitops
          ssh-key: ${{ secrets.GIT_OPS_SSH_KEY }}
          ref: main

      - name: Install Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update Kubernetes resources
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Navega a la carpeta de la app
          cd apps/${{ inputs.app_name }}

          # Actualiza el tag de la imagen usando kustomize
          kustomize edit set image ghcr.io/medaqueno/k8s-lab-apps-${{ inputs.app_name }}=ghcr.io/medaqueno/k8s-lab-apps-${{ inputs.app_name }}:${{ needs.build-and-push.outputs.image_tag }}

          # Commit y push
          git add kustomization.yaml
          git commit -m "update image tag for ${{ inputs.app_name }} to ${{ needs.build-and-push.outputs.image_tag }}" || echo "No changes to commit"
          git push
