#Este archivo es el que le dice a ArgoCD: "Vigila esta carpeta y mantén el clúster igual". Lo guardarás en k8s-gitops/argo-apps/python-api-1-app.yaml.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-api-1-prod
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: "https://github.com/medaqueno/k8s-lab-gitops.git"
    targetRevision: HEAD
    path: apps/python-api-1/overlays/prod # Donde está el kustomization
  destination:
    server: "https://kubernetes.default.svc"
    namespace: python-api-1-prod
  syncPolicy:
    automated:
      prune: true # Borra lo que quites del Git
      selfHeal: true # Si alguien cambia algo a mano, Argo lo revierte
    syncOptions:
      - CreateNamespace=true # Crea el namespace si no existe
